# Generated by Django 6.0.5 on 2026-06-11 01:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
